title: Haigui-ckh
description: Personal site
baseurl: ""
# GitHub Pages 部署时会自动设置正确的 URL
# 本地开发时可以临时改为 "http://localhost:4000"
url: ""
# 使用 Beautiful Jekyll 主题
theme: beautiful-jekyll-theme
# 启用 RSS 插件
plugins:
  - jekyll-feed
# 导航链接（Beautiful Jekyll）
navbar-links:
  关于: "/about/"
exclude:
  - .qodo
  - README.md
  - Gemfile
  - Gemfile.lock